module.exports = ({
    path: '/imagegen/leaderboard',
    details: { description: 'Genera tabla de posiciones de 10 lugares.' },
    code: `
$setVar[requestCount;$math[$getVar[requestCount] + 1]]
$send[200;canvas;$default]
$ignore[Positions part]

  $ignore[Position 10]
    $drawText[$get[pos10TextCutter];120;675;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;678;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[10;48;675;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;678;54;54]
    $color[#FFFFFF]
    $var[pos10TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos10TextReplacer]]>26];true;$slice[$get[pos10TextReplacer];1;26]];false;$get[pos10TextReplacer]]]
  $var[pos10TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos10user]!=undefined&&$getQuery[pos10value]!=undefined];true;$getQuery[pos10value] - $getQuery[pos10user]];false;UNDEFINED!]]
  $ignore[End position 10]

  $ignore[Position 9]
    $drawText[$get[pos9TextCutter];120;595;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;603;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[9;48;595;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;603;54;54]
    $color[#FFFFFF]
    $var[pos9TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos9TextReplacer]]>26];true;$slice[$get[pos9TextReplacer];1;26]];false;$get[pos9TextReplacer]]]
  $var[pos9TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos9user]!=undefined&&$getQuery[pos9value]!=undefined];true;$getQuery[pos9value] - $getQuery[pos9user]];false;UNDEFINED!]]
  $ignore[End position 9]


  $ignore[Position 8]
    $drawText[$get[pos8TextCutter];120;525;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;530;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[8;48;525;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;530;54;54]
    $color[#FFFFFF]
    $var[pos8TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos8TextReplacer]]>26];true;$slice[$get[pos8TextReplacer];1;26]];false;$get[pos8TextReplacer]]]
  $var[pos8TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos8user]!=undefined&&$getQuery[pos8value]!=undefined];true;$getQuery[pos8value] - $getQuery[pos8user]];false;UNDEFINED!]]
  $ignore[End position 8]

  $ignore[Position 7]
    $drawText[$get[pos7TextCutter];120;450;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;456;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[7;48;455;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;460;54;54]
    $color[#FFFFFF]
    $var[pos7TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos7TextReplacer]]>26];true;$slice[$get[pos7TextReplacer];1;26]];false;$get[pos7TextReplacer]]]
  $var[pos7TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos7user]!=undefined&&$getQuery[pos7value]!=undefined];true;$getQuery[pos7value] - $getQuery[pos7user]];false;UNDEFINED!]]
  $ignore[End position 7]

  $ignore[Position 6]
    $drawText[$get[pos6TextCutter];120;378;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;383;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[6;48;380;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;383;54;54]
    $color[#FFFFFF]
    $var[pos6TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos6TextReplacer]]>26];true;$slice[$get[pos6TextReplacer];1;26]];false;$get[pos6TextReplacer]]]
  $var[pos6TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos6user]!=undefined&&$getQuery[pos6value]!=undefined];true;$getQuery[pos6value] - $getQuery[pos6user]];false;UNDEFINED!]]
  $ignore[End position 6]

  $ignore[Position 5]
    $drawText[$get[pos5TextCutter];120;309;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;309;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[5;48;309;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;316;54;54]
    $color[#FFFFFF]
    $var[pos5TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos5TextReplacer]]>26];true;$slice[$get[pos5TextReplacer];1;26]];false;$get[pos5TextReplacer]]]
  $var[pos5TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos5user]!=undefined&&$getQuery[pos5value]!=undefined];true;$getQuery[pos5value] - $getQuery[pos5user]];false;UNDEFINED!]]
  $ignore[End position 5]

  $ignore[Position 4]
    $drawText[$get[pos4TextCutter];120;235;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;238;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[4;48;240;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;245;54;54]
    $color[#FFFFFF]
    $var[pos4TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos4TextReplacer]]>26];true;$slice[$get[pos4TextReplacer];1;26]];false;$get[pos4TextReplacer]]]
  $var[pos4TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos4user]!=undefined&&$getQuery[pos4value]!=undefined];true;$getQuery[pos4value] - $getQuery[pos4user]];false;UNDEFINED!]]
  $ignore[End position 4]

  $ignore[Position 3]
    $drawText[$get[pos3TextCutter];120;165;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;165;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[3;48;165;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;168;54;54]
    $color[#FFFFFF]
    $var[pos3TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos3TextReplacer]]>26];true;$slice[$get[pos3TextReplacer];1;26]];false;$get[pos3TextReplacer]]]
  $var[pos3TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos3user]!=undefined&&$getQuery[pos3value]!=undefined];true;$getQuery[pos3value] - $getQuery[pos3user]];false;UNDEFINED!]]
  $ignore[End position 3]

  $ignore[Position 2]
    $drawText[$get[pos2TextCutter];120;86;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;90;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[2;48;89;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;95;54;54]
    $color[#FFFFFF]
    $var[pos2TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos2TextReplacer]]>26];true;$slice[$get[pos2TextReplacer];1;26]];false;$get[pos2TextReplacer]]]
  $var[pos2TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos2user]!=undefined&&$getQuery[pos2value]!=undefined];true;$getQuery[pos2value] - $getQuery[pos2user]];false;UNDEFINED!]]
  $ignore[End position 2]

  $ignore[Position 1]
    $drawText[$get[pos1TextCutter];120;10;600;65;left]
    $color[#FFFFFF]
    $opacity[100]
    $drawRect[110;15;600;65]
    $opacity[30]
    $color[#FFFFFF]
    $drawText[1;48;18;54;54]
    $color[#000000]
    $font[40;UniSans]
    $drawRect[48;22;54;54]
    $color[#FFFFFF]
    $var[pos1TextCutter;$replaceText[$replaceText[$condition[$charCount[$get[pos1TextReplacer]]>26];true;$slice[$get[pos1TextReplacer];1;26]];false;$get[pos1TextReplacer]]]
  $var[pos1TextReplacer;$replaceText[$replaceText[$condition[$getQuery[pos1user]!=undefined&&$getQuery[pos1value]!=undefined];true;$getQuery[pos1value] - $getQuery[pos1user]];false;UNDEFINED!]]
  $ignore[End position 1]
$registerFont[./assets/fonts/UniSansHeavy.otf;UniSans]
$ignore[End Positions part]

$ignore[Background part]
  $drawImage[bg;0;0;720;785]
  $createCanvas[720;785]
  $if[$isImage[bg]==false;400;{
"status": 400,
"error": "Invalid image provided in: background"
  }]
  $loadImage[bg;$get[bgTypeReplacer];$get[bgReplacer]]
  $var[bgReplacer;$replaceText[$replaceText[$condition[$getQuery[background]==undefined];true;./assets/images/BlackBG.jpg];false;$getQuery[background]]]
  $var[bgTypeReplacer;$replaceText[$replaceText[$condition[$getQuery[background]==undefined];true;path];false;link]]
$ignore[End Background Part]
`
})